name: Deploy Images to GHCR


on:
  push:
    branches:
      - main
  workflow_dispatch:


jobs:
  push-store-image:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@main
      
      - name: 'Login to GitHub Container Registry'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          
      - name: 'Build Inventory Image'
        working-directory: ./
        run: docker build . --tag ghcr.io/tadiesse/store:latest
          
      - name: Install Cosign
        uses: sigstore/cosign-installer@v3.1.1


      - name: Write signing key to disk
        run: 'echo "$KEY" > cosign.key'
        shell: bash
        env:
          KEY: ${{ secrets.COSIGN_PRIVATE_KEY }}


      - name: Sign the published Docker image
        env:
          COSIGN_PASSWORD: ${{ secrets.COSIGN_PASSWORD }}
        run: cosign sign --key cosign.key ghcr.io/tadiesse/store:latest


      - name: Push the signed image on GHCR
        run: docker push ghcr.io/tadiesse/store:latest
