name: Build and Publish Docker Image to GHCR

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build Docker Image
      run: |
        docker buildx build \
          --file Dockerfile \
          --tag ghcr.io/${{ github.repository }}/hello-world:latest \
          .
      working-directory: ./  # Path to your Dockerfile

    - name: Publish Docker Image to GHCR
      run: |
        echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
        docker push ghcr.io/${{ github.repository }}/hello-world:latest

    - name: Cleanup
      run: docker logout ghcr.io
