name: Deploy Images to GHCR

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  push-store-image:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@main

      - name: Install Cosign
        uses: sigstore/cosign-installer@v3.1.1

      - name: 'Login to GitHub Container Registry'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: 'Build Inventory Image'
        working-directory: ./
        run: |
          docker build . --tag ghcr.io/tadiesse/store:latest
          docker push ghcr.io/tadiesse/store:latest

      - name: Generate and Sign with a New Key
        run: |
          cosign generate-key-pair
          cosign sign --yes ghcr.io/tadiesse/store:latest
